{{- if .Values.services.etlworks.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-entrypoint-config
  namespace: {{ .Values.services.etlworks.namespace }}
data:
  entrypoint.sh: |-
{{ .Values.services.etlworks.deployment.entrypointConfig | indent 4 }}
{{ end }}

{{- if .Values.services.etlworks.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-download-config
  namespace: {{ .Values.services.etlworks.namespace }}
data:
  download.sh: |-
{{ .Values.services.etlworks.deployment.downloadConfig | indent 4 }}
{{ end }}