apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-embeddings-inference
  namespace: duploservices-stg-01 
  labels:
    app: genai-embeddings-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-embeddings-inference
  template:
    metadata:
      labels:
        app: genai-embeddings-inference
    spec:
      nodeSelector:
        tenantname: duploservices-stg-01    
      containers:
        - name: genai-embeddings-inference
          image: ghcr.io/huggingface/text-embeddings-inference:cpu-0.6
          args:
            - "--model-id=BAAI/bge-large-en-v1.5"
            - "--revision=refs/pr/5"
            - "--port=8080"
            - "--json-output"
          ports:
            - containerPort: 8080
              protocol: TCP
          env: [] 
          resources:
            requests:
              memory: "16384Mi"
              cpu: "8192m"
            limits:
              memory: "16384Mi"
              cpu: "8192m"

---
apiVersion: v1
kind: Service
metadata:
  name: genai-embeddings-inference
  namespace: duploservices-stg-01
  labels:
    app: genai-embeddings-inference
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-00507881a9d442a00, subnet-0c4b81b03e65a4ebf
    external-dns.alpha.kubernetes.io/hostname: ai-embeddings-inference-staging-authorium-staging-stg-01.authorium.com
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0bf3248f559608753, sg-07e88d2f9bdb09a92
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws-us-gov:acm:us-gov-west-1:070029289390:certificate/33353efb-210b-4a9b-80c4-7df5a5eca554"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  selector:
    app: genai-embeddings-inference
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
