apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-pdf-nlm-ingestor
  namespace: duploservices-stg-01  
  labels:
    app: genai-pdf-nlm-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-pdf-nlm-ingestor
  template:
    metadata:
      labels:
        app: genai-pdf-nlm-ingestor
    spec:
      nodeSelector:
        tenantname: duploservices-stg-01
      containers:
      - name: genai-pdf-nlm-ingestor
        image: 070029289390.dkr.ecr.us-gov-west-1.amazonaws.com/pdf-nlm-ingestor:11182024-amdx86_64
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "1000m"
            memory: "2048Mi"
          limits:
            cpu: "3000m"
            memory: "6144Mi"
        env: []  
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
        volumeMounts: []  
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: genai-pdf-nlm-ingestor
  namespace: duploservices-stg-01
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-00507881a9d442a00, subnet-0c4b81b03e65a4ebf
    external-dns.alpha.kubernetes.io/hostname: ai-pdf-nml-ingestor-staging-authorium-staging-stg-01.authorium.com
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0bf3248f559608753, sg-07e88d2f9bdb09a92
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws-us-gov:acm:us-gov-west-1:070029289390:certificate/33353efb-210b-4a9b-80c4-7df5a5eca554"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
  labels:
    app: genai-pdf-nlm-ingestor
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  ports:
  - port: 443
    targetPort: 5001
    protocol: TCP
  selector:
    app: genai-pdf-nlm-ingestor