{{- if .Values.services.appsidekiq.initialuser }}
apiVersion: batch/v1
kind: Job
metadata:
  name: initial-user-5
  namespace: {{ .Values.services.appsidekiq.namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    rubix-app: {{ .Chart.Name }}
  {{- with .Values.services.appsidekiq.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 600
  activeDeadlineSeconds: 900
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/component: migrate
        rubix-app: {{ .Chart.Name }}
      annotations:
        com.palantir.rubix.pod/sls-service-info-v2: |
          {
            "ServiceName": "{{ .Release.Name }}",
            "ServiceID": "{{ .Release.Namespace }}-{{ .Release.Name }}",
            "StackName": "{{ .Release.Namespace }}",
            "StackID": "{{ .Release.Namespace }}",
            "Containers": {
              "appsidekiq-app-sidekiq": {
                "ProductName": "{{ .Chart.Name }}",
                "ProductVersion": "{{ .Chart.AppVersion }}"
              }
            }
          }
        com.palantir.rubix.service/pod-cert: '{}'
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: com.palantir.rubix/instance-group
                    operator: In
                    values:
                      - fedstart
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: {{ .Release.Name }}
                topologyKey: topology.kubernetes.io/zone
              weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
      containers:
        - name: main
          workingDir: /rails
          image: "{{ .Values.services.appsidekiq.deployment.image.repository }}:{{ .Values.services.appsidekiq.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.services.appsidekiq.deployment.image.pullPolicy | default "IfNotPresent" }}
          command: ["/bin/sh","-lc"]
          args:
            - |
              bin/rails r "
                u = User.find_or_initialize_by(email: 'engineering@appsidekiq.com')
                u.first_name = 'appsidekiq'
                u.last_name  = 'Engineering'
                u.password   = ENV.fetch('appsidekiq_ADMIN_PASSWORD')
                u.terms_of_service = true
                u.admin = true
                u.skip_default_organization = true if u.respond_to?(:skip_default_organization=)
                u.save!

                org = Organization.find_or_create_by!(name: 'Test Organization')
                Membership.find_or_create_by!(organization: org, user: u) { |m| m.role = :owner }

                puts 'Ensured admin user and org created'
              "
          env:
            {{- range .Values.services.appsidekiq.deployment.config.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            {{- range $key, $value := .Values.services.appsidekiq.deployment.config.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name }}
                  key: {{ $value.key }}
            {{- end }}
          #securityContext:
          #  runAsUser: 10001
          #  runAsGroup: 10001
          #  runAsNonRoot: true
          volumeMounts:
            - name: external-ca-bundle
              mountPath: /usr/local/share/ca-certificates/fed-ca.pem
              subPath: ca.pem
              readOnly: true  
            - name: tmp-home
              mountPath: /tmp/home
              readOnly: false  
      volumes:
        - name: redis-ca
          secret:
            secretName:  cert-appsidekiq-app-redis-4
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
              - key: ca.crt
                path: ca.crt
        - name: external-ca-bundle
          configMap:
            name: tls-external-ca-bundle
            items:
              - key: ca.pem
                path: ca.pem
        - name: ca-bundle
          emptyDir: {}
{{- end }}
