{{- $ns := .Release.Namespace -}}
{{- $s := lookup "v1" "Secret" $ns "appsidekiq-redis" -}}
{{- if $s }}
{{- $pass := index $s.data "redis-password" | b64dec -}}
apiVersion: v1
kind: Secret
metadata:
  name: appsidekiq-redis-url
  namespace: {{ $ns }}
type: Opaque
stringData:
  REDIS_URL: rediss://:{{ $pass }}@appsidekiq-redis-master.appsidekiq.svc.cluster.local:6379/0
{{- end }}
