{{- if .Values.services.etlworks.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Values.services.etlworks.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.services.etlworks.storage.storageClass }}
  resources:
    requests:
      storage: 10Gi
{{ end }}