apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-api
  namespace: duploservices-stg-01
  labels:
    app: genai-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-api
  template:
    metadata:
      labels:
        app: genai-api
    spec:
      nodeSelector:
        tenantname: duploservices-stg-01
      containers:
        - name: genai-api
          image: 070029289390.dkr.ecr.us-gov-west-1.amazonaws.com/docshunter-genai-ai-api:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: PDF_TO_MD_URL
              value: "https://ai-pdf-nml-ingestor-staging-authorium-staging-stg-01.secure.authorium.com/api/parseDocument?renderFormat=all&useNewIndentParser=true"
            - name: APP_ENV
              value: "staging"
            - name: EXTRACT_DOCUMENT_NAME
              value: "False"
            - name: LLM_HOSTING
              value: "BEDROCK"
            - name: INFER_PROMPT_TYPE
              value: "False"
            - name: BEDROCK_REGION
              value: "us-gov-west-1"
            - name: RE_RANKER_MODEL
              value: "rerank-english-v3.0"
            - name: LLM_ASK_TEMPERATURE
              value: "0.1"
            - name: PROMPT_TYPE
              value: "TEXT_GENERATION"
            - name: EMBEDDINGS_API_URL
              value: "https://ai-embeddings-inference-staging-authorium-staging-stg-01.secure.authorium.com/embed"
            - name: LLM_MODEL_ID
              value: "meta.llama3-70b-instruct-v1:0"
            - name: APP_PORT
              value: "8000"
            - name: LLM_MODEL
              value: "CLAUDE"
            - name: SYSTEM_ORGANIZATION_ID
              valueFrom:
                secretKeyRef:
                  name: genai-api-secrets
                  key: SYSTEM_ORGANIZATION_ID
            - name: COHERE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-api-secrets
                  key: COHERE_API_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: genai-api-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: genai-api-secrets
                  key: JWT_SECRET
            - name: AUTHORIZED_API_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-api-secrets
                  key: AUTHORIZED_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-api-secrets
                  key: OPENAI_API_KEY
            - name: AWS_S3_DOCUMENTS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: genai-api-secrets
                  key: AI_S3_BUCKET_NAME
          resources:
            requests:
              cpu: "2048m"
              memory: "4096Mi"
            limits:
              cpu: "2048m"
              memory: "4096Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: aws-logs
              mountPath: /var/log/containers
      volumes:
        - name: aws-logs
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: genai-api-service
  namespace: duploservices-stg-01
  labels:
    app: genai-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-00507881a9d442a00, subnet-0c4b81b03e65a4ebf
    external-dns.alpha.kubernetes.io/hostname: ai-staging-authorium-staging-stg-01.authorium.com
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0bf3248f559608753, sg-07e88d2f9bdb09a92
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws-us-gov:acm:us-gov-west-1:070029289390:certificate/33353efb-210b-4a9b-80c4-7df5a5eca554"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  selector:
    app: genai-api
  ports:
    - port: 443
      targetPort: 8000
      protocol: TCP