apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-formio
spec:
  capacity:
    storage: 5Gi  # This is a placeholder; EFS provides virtually unlimited storage.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # EFS supports multiple nodes accessing the volume
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-01b83e37f4b29309c  # Your EFS ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-formio
  namespace: duploservices-stg-3p01
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""  # Leave empty to use the default storage class (no provisioner needed)
  resources:
    requests:
      storage: 5Gi  # Placeholder; actual storage size is not limited

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: formio-enterprise-pvc
#   namespace: duploservices-stg-3p01
#   labels:
#     app: formio-enterprise  
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: aws-efs
#   resources:
#     requests:
#       storage: 5Gi

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: formio-enterprise-pv
#   namespace: duploservices-stg-3p01  
#   labels:
#     app: formio-enterprise
# spec:
#   capacity:
#     storage: 5Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: aws-efs
#   csi:
#     driver: efs.csi.aws.com
#     volumeHandle: fs-01b83e37f4b29309c

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formio-enterprise
  namespace: duploservices-stg-3p01
  labels:
    app: formio-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formio-enterprise
  template:
    metadata:
      labels:
        app: formio-enterprise
    spec:
      nodeSelector:
        tenantname: duploservices-stg-3p01
      containers:
        - name: formio-enterprise
          image: 070029289390.dkr.ecr.us-gov-west-1.amazonaws.com/form-io-enterprise:9.0.2-202411.1397
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: DEBUG
              value: "*.*"
            - name: PDF_SERVER
              value: "https://innovate-forms-pdf-server-stg-3p01.secure.authorium.com" # Make this dynamic via values.yaml
            - name: ENABLE_SSL
              value: "true"
            - name: PORTAL_ENABLED
              value: "1"
            - name: MONGO_CA
              value: "/etc/rds/us-gov-west-1-bundle.pem"
            - name: MONGO
              valueFrom:
                secretKeyRef:
                  name: formio-secrets
                  key: MONGO
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: formio-secrets
                  key: LICENSE_KEY
            - name: SSL_KEY
              valueFrom:
                secretKeyRef:
                  name: formio-secrets
                  key: SSL_KEY
            - name: SSL_CERT
              valueFrom:
                secretKeyRef:
                  name: formio-secrets
                  key: SSL_CERT
            - name: PORTAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: formio-secrets
                  key: PORTAL_SECRET
            - name: DB_SECRET
              valueFrom:
                secretKeyRef:
                  name: formio-secrets
                  key: DB_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: formio-secrets
                  key: FORMIO_JWT_SECRET_KEY
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: formio-secrets
                  key: ADMIN_EMAIL
            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: formio-secrets
                  key: ADMIN_PASS
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - mountPath: /etc/rds
              name: formio-ca-bundle
              readOnly: true
            # - mountPath: /efs
            #   name: formio-enterprise-pv
          securityContext:
            readOnlyRootFilesystem: false
            privileged: false
      volumes:
        - name: formio-ca-bundle
          persistentVolumeClaim:
            claimName: pvc-formio
        # - name: formio-enterprise-pv
        #   persistentVolumeClaim:
        #     claimName: formio-enterprise-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: formio-enterprise-service
  namespace: duploservices-stg-3p01
  labels:
    app: formio-enterprise
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-00507881a9d442a00, subnet-0c4b81b03e65a4ebf
    external-dns.alpha.kubernetes.io/hostname: innovate-forms-stg-3p01.authorium.com
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0bf3248f559608753, sg-07e88d2f9bdb09a92
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws-us-gov:acm:us-gov-west-1:070029289390:certificate/33353efb-210b-4a9b-80c4-7df5a5eca554"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  selector:
    app: formio-enterprise
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP