services:

  ckedocx: 
    create: true
      
    namespace: authorium

    deployment_nginx:
      replicas: 1
      image:
        repository: "070029289390.dkr.ecr-fips.us-gov-west-1.amazonaws.com/nginx"
        tag: "1.29.3-202511.2725-alpine"
        pullPolicy: Always
      containerPort: 8081
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"
      annotations: {}
      config:
        env:
        - name: APP_PORT
          value: "8080"
        - name: NGINX_PORT
          value: "8081"
        - name: APP_PROTOCOL
          value: "http"
        - name: SSL_CERT
          value: tls
      nginxConfig: |
        # This config file was created by cke-docx-values.yaml
        pid /tmp/nginx.pid;
        
        # verbose logging
        error_log /dev/stderr debug;
        
        events {}
        
        http {
          # NGINX will handle gzip compression of responses from the app server
          gzip on;
          gzip_proxied any;
          gzip_types text/plain application/json;
          gzip_min_length 1000;
        
          server {
            listen NGINX_PORT ssl;
            ssl_certificate         /etc/ssl/SSL_CERT.crt;
            ssl_certificate_key     /etc/ssl/SSL_CERT.key;
        
            client_max_body_size 500M;
        
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_prefer_server_ciphers on;
            ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            # ssl_stapling on; # Commented out as we're using self-signed certs, revisit later
            # ssl_stapling_verify on; # Commented out as we're using self-signed certs, revisit later
            add_header Strict-Transport-Security max-age=15768000;
        
            location / {
              proxy_pass APP_PROTOCOL://localhost:APP_PORT/;
              PROXY_SSL_VERIFY
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_cache_bypass $http_upgrade;
              proxy_buffering off;
              proxy_ignore_client_abort off;
              break;
            }
          }
        }

    deployment:
      replicas: 1
      image:
        #repository: 070029289390.dkr.ecr-fips.us-gov-west-1.amazonaws.com/hisec-docx
        repository: "070029289390.dkr.ecr-fips.us-gov-west-1.amazonaws.com/vendor/cke-docx"
        tag: "1.22.2-202510.2581"
        #tag: "1.22.2"
        pullPolicy: Always
      containerPort: 8080
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
      annotations: {}           
      config:
        env:
        - name: CONFIG_ENV
          value: "staging"
        - name: SSL_CERT
          value: tls
        - name: ENABLE_METRIC_LOGS
          value: "true"
        - name: LOG_LEVEL
          value: "30"                      
        secrets:
          LICENSE_KEY:
            name: cke-docx-ckedocx
            key: LICENSE_KEY       

    service:
      type: ClusterIP
      loadBalancerClass: service.k8s.aws/nlb
      port: 443  
      annotations:
        com.palantir.rubix.service.spp/v3: >
          {
              "endpoints":[
              {
                "name":"http-svc",
                "prefix":"/",
                "domain-aliases":["DOCX"]
              }
            ]
          }
        com.palantir.rubix.service/pod-cert: '{}'

    #service:
    #  type: ClusterIP
    #  port: 443  
    #  annotations:
    #    com.palantir.rubix.service.spp/v3: >
    #      {
    #          "endpoints":[
    #            {
    #              "name":"http-svc",
    #              "prefix":"/docx",
    #              "domain-aliases":["DEFAULT"]
    #            },
    #            {
    #              "name":"http-svc",
    #              "prefix":"/docs",
    #              "domain-aliases":["DEFAULT"]
    #            },
    #            {
    #              "name":"http-svc",
    #              "prefix":"/api/",
    #              "domain-aliases":["DEFAULT"]
    #            },
    #            {
    #              "name":"http-svc",
    #              "prefix":"/v2/convert/",
    #              "domain-aliases":["DEFAULT"]
    #            }
    #          ]
    #      }
    #    com.palantir.rubix.service/pod-cert: '{}'

