{{- if .Values.services.ckedocx.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.services.ckedocx.namespace }}
data:
  nginx.conf: |-
{{ .Values.services.ckedocx.deployment_nginx.nginxConfig | indent 4 }}
{{ end }}