services:

  authoriumDocsProxy:
    create: true

    namespace: authorium

    deployment_nginx:
      replicas: 1
      image:
        repository: "070029289390.dkr.ecr-fips.us-gov-west-1.amazonaws.com/nginx"
        tag: "1.29.3-202511.2725-alpine"
        pullPolicy: Always
      containerPort: 9443
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"
      annotations: {}
      config:
        env:
        - name: APP_PORT
          value: "3000"
        - name: NGINX_PORT
          value: "9443"
        - name: APP_PROTOCOL
          value: "http"
        - name: SSL_CERT
          value: tls

    serviceaccount:
      name: s3-service-account
      automountServiceAccountToken: true

    deployment:
      replicas: 1
      image:
        repository: 070029289390.dkr.ecr-fips.us-gov-west-1.amazonaws.com/authorium-docs-proxy
        tag: "1.0.11"
        pullPolicy: Always
      containerPort: 3000
      resources:
        limits:
          cpu: "512m"
          memory: "1024Mi"
      annotations: {}
      config:
        env:
        - name: AWS_REGION
          value: "us-gov-west-1"
        - name: AWS_S3_BUCKET
          value: "391c760e-authorium-app2025091715004350480000000"
        - name: RAILS_SSO_URL
          value: "https://authorium-app-stg.palantirfedstart.com/service_auth/writedocs"
          # value: "https://app.staging.authorium.com/service_auth/writedocs"
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: AWS_ROLE_ARN
          value: "arn:aws-us-gov:iam::322658992871:role/391c760e-fedstart-default-role-04770bd5"
        - name: AWS_USE_FIPS_ENDPOINT
          value: "true"
        secrets:
          JWT_SECRET:
            name: authorium-app-sidekiq-secrets
            key: WRITEDOCS_JWT_SHARED_SECRET

    service:
      type: ClusterIP
      port: 443  
      annotations:
        com.palantir.rubix.service.spp/v3: >
          {
              "endpoints":[{
                  "name":"http-svc",
                  "prefix":"/", 
                  "domain-aliases":["DOCS-PROXY"]
              }]
          }
        com.palantir.rubix.service/pod-cert: '{}'

    # service:
    #   type: LoadBalancer
    #   loadBalancerClass: service.k8s.aws/nlb
    #   port: 443
    #   annotations:
    #     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    #     service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-00507881a9d442a00, subnet-0c4b81b03e65a4ebf
    #     external-dns.alpha.kubernetes.io/hostname: authorium-docs-proxy-stg-01.authorium.com
    #     service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
    #     service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    #     service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0bf3248f559608753, sg-07e88d2f9bdb09a92
    #     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws-us-gov:acm:us-gov-west-1:070029289390:certificate/33353efb-210b-4a9b-80c4-7df5a5eca554"
    #     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    #     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    #     service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
