{{- if .Values.services.ckecore.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.services.ckecore.namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    rubix-app: {{ .Chart.Name }}
  {{- with .Values.services.ckecore.deployment.annotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  replicas: {{ .Values.services.ckecore.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/component: server
        rubix-app: {{ .Chart.Name }}
      annotations:
        com.palantir.rubix.pod/sls-service-info-v2: |
          {
            "ServiceName": "{{ .Release.Name }}",
            "ServiceID": "{{ .Release.Namespace }}-{{ .Release.Name }}",
            "StackName": "{{ .Release.Namespace }}",
            "StackID": "{{ .Release.Namespace }}",
            "Containers": {
              "nginx": {
                "ProductName": "{{ .Chart.Name }}",
                "ProductVersion": "{{ .Chart.AppVersion }}"
              },
              "cke-core": {
                "ProductName": "{{ .Chart.Name }}",
                "ProductVersion": "{{ .Chart.AppVersion }}"
              }              
            }
          }
        com.palantir.rubix.service/pod-cert: '{}'
    spec:
      automountServiceAccountToken: true
      serviceAccountName: s3-service-account
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: com.palantir.rubix/instance-group
                    operator: In
                    values:
                      - fedstart
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: {{ .Release.Name }}
                topologyKey: topology.kubernetes.io/zone
              weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
      ##initContainers:
      ##  - name: s3-irsa-check
      ##    image: 070029289390.dkr.ecr-fips.us-gov-west-1.amazonaws.com/aws-cli:2.15.57
      ##    command:
      ##      - /bin/sh
      ##      - -c
      ##      - |
      ##        echo "Verifying identity with IRSA..."
      ##        aws sts get-caller-identity || { echo "❌ STS identity failed"; exit 1; }
      ##        echo "Checking access to S3 bucket..."
      ##        aws s3 ls s3://391c760e-cots-repo20250408151611135500000002 --region us-gov-west-1 || { echo "❌ S3 access denied"; exit 1; }
      ##        echo "✅ IRSA and S3 bucket access verified."
      ##    env:
      ##      - name: HOME
      ##        value: "/tmp/home"
      ##      - name: AWS_USE_FIPS_ENDPOINTS
      ##        value: "true"                       
      ##      {{- range $key, $value := .Values.services.ckecore.deployment.config.secrets }}
      ##      - name: {{ $key }}
      ##        valueFrom:
      ##          secretKeyRef:
      ##            name: {{ $value.name }}
      ##            key: {{ $value.key }}
      ##      {{- end }}
      ##      {{- range .Values.services.ckecore.deployment.config.env }}
      ##      - name: {{ .name }}
      ##        value: "{{ .value }}"
      ##      {{- end }}  
      ##    securityContext:
      ##      runAsUser: 10001
      ##      runAsGroup: 10001
      ##      runAsNonRoot: true
      ##    volumeMounts:
      ##      - name: external-ca-bundle
      ##        mountPath: /usr/local/share/ca-certificates/fed-ca.pem
      ##        subPath: ca.pem
      ##        readOnly: true  
      ##      - name: tmp-home
      ##        mountPath: /tmp/home
      ##        readOnly: false          

      containers:    
        - name: nginx
          image: "{{ .Values.services.ckecore.deployment_nginx.image.repository }}:{{ .Values.services.ckecore.deployment_nginx.image.tag }}"
          imagePullPolicy: {{ .Values.services.ckecore.deployment_nginx.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.services.ckecore.deployment_nginx.containerPort }}
              protocol: TCP
              name: http-svc
          volumeMounts:
            - name: tls-secret-volume
              mountPath: /etc/ssl/
              readOnly: true                 
          env:
            {{- range $key, $value := .Values.services.ckecore.deployment_nginx.config.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name }}
                  key: {{ $value.key }}
            {{- end }}
            {{- range .Values.services.ckecore.deployment_nginx.config.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          resources:
            requests:
              memory: {{ .Values.services.ckecore.deployment_nginx.resources.requests.memory }}
              cpu: {{ .Values.services.ckecore.deployment_nginx.resources.requests.cpu }}
            limits:
              memory: {{ .Values.services.ckecore.deployment_nginx.resources.limits.memory }}
              cpu: {{ .Values.services.ckecore.deployment_nginx.resources.limits.cpu }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault               

        - name: cke-core
          image: "{{ .Values.services.ckecore.deployment.image.repository }}:{{ .Values.services.ckecore.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.services.ckecore.deployment.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.services.ckecore.deployment.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: redis-ca
              mountPath: /etc/ssl/
              readOnly: true 
            - name: external-ca-bundle
              mountPath: /usr/local/share/ca-certificates/fed-ca.pem
              subPath: ca.pem
              readOnly: true          
          env:
            {{- range $key, $value := .Values.services.ckecore.deployment.config.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name }}
                  key: {{ $value.key }}
            {{- end }}
            {{- range .Values.services.ckecore.deployment.config.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}          
          resources:      
            limits:
              cpu: {{ .Values.services.ckecore.deployment.resources.limits.cpu }}
              memory: {{ .Values.services.ckecore.deployment.resources.limits.memory }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          #livenessProbe:
          #  httpGet:
          #    path: /health
          #    port: 8080
          #  initialDelaySeconds: 20
          #  periodSeconds: 20
          #  failureThreshold: 10
          #  timeoutSeconds: 5
      restartPolicy: Always
      volumes:
        - name: tls-secret-volume
          secret:
            secretName: cert-cke-core
        - name: redis-ca
          secret:
            secretName:  cert-cke-core-redis-4
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        - name: external-ca-bundle
          configMap:
            name: tls-external-ca-bundle
            items:
              - key: ca.pem
                path: ca.pem
        - name: tmp-home
          emptyDir: {}
{{ end }}