apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-service-account
  namespace: authorium
  annotations:
    eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::322658992871:role/391c760e-fedstart-default-role-04770bd5  