services:

  genaiembeddings: 
    create: true
      
    namespace: authorium

    deployment_nginx:
      image:
        repository: "070029289390.dkr.ecr-fips.us-gov-west-1.amazonaws.com/nginx"
        tag: "1.29.3-202511.2725-alpine"
        pullPolicy: Always
      containerPort: 9443
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"
      annotations: {}
      config:
        env:
        - name: APP_PORT
          value: "8080"
        - name: NGINX_PORT
          value: "9443"
        - name: APP_PROTOCOL
          value: "https"
        - name: SSL_CERT
          value: tls

    deployment:
      replicas: 1
      image:
        repository: 070029289390.dkr.ecr-fips.us-gov-west-1.amazonaws.com/text-embeddings-inference
        tag: "0.1.4"
        pullPolicy: Always
      containerPort: 8080
      resources:
        limits:
          cpu: "6144m"
          memory: "12288Mi"
      annotations: {}

    service:
      type: ClusterIP
      port: 443  
      annotations:
        com.palantir.rubix.service/pod-cert: '{}'  

