{{- if and .Values.services .Values.services.wave .Values.services.wave.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wave-svc
  namespace: {{ .Values.services.wave.namespace }}
  labels:
    app: wave
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: wave
    app.kubernetes.io/component: server
    rubix-app: {{ .Chart.Name }}
  {{- with .Values.services.wave.service.annotations }}    
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec: 
  type: {{ .Values.services.wave.service.type | default "ClusterIP" }}
  {{- if eq .Values.services.wave.service.type "LoadBalancer" }}
  loadBalancerClass: {{ .Values.services.wave.service.loadBalancerClass }}
  {{- end }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: wave
  ports:
    - name: http-svc
      port: {{ .Values.services.wave.service.port }}
      targetPort: {{ .Values.services.wave.deployment.containerPort }}
      protocol: TCP
{{ end }}
