{{- if .Values.services.formioenterprise.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.services.formioenterprise.namespace }}
  labels:
    app: formio-enterprise
  {{- with .Values.services.formioenterprise.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.formioenterprise.service.type }}
  loadBalancerClass: {{ .Values.services.formioenterprise.service.loadBalancerClass }}
  selector:
    app: formio-enterprise
  ports:
    - name: http-svc
      port: {{ .Values.services.formioenterprise.service.port }}
      targetPort: {{ .Values.services.formioenterprise.deployment_nginx.containerPort }}
      protocol: TCP
{{ end }}
