apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-service-account
  namespace: authorium
  annotations:
    eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::322658992871:role/391c760e-mission-manager-bedrock-default-role-bb70d24b  