services:

  genaipdf: 
    create: true
      
    namespace: authorium

    deployment_nginx:
      image:
        repository: "070029289390.dkr.ecr-fips.us-gov-west-1.amazonaws.com/nginx"
        tag: "1.29.3-202511.2725-alpine"
        pullPolicy: Always
      containerPort: 9443
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"
      annotations: {}
      config:
        env:
        - name: APP_PORT
          value: "8443"
        - name: NGINX_PORT
          value: "9443"
        - name: APP_PROTOCOL
          value: "https"
        - name: SSL_CERT
          value: tls

    deployment:
      replicas: 1
      image:
        repository: "070029289390.dkr.ecr-fips.us-gov-west-1.amazonaws.com/pdf-nlm-ingestor"
        tag: "0.1.5"
        pullPolicy: Always
      containerPort: 5001
      resources:
        limits:
          cpu: "3000m"
          memory: "6144Mi"
        #requests:
        #  cpu: "3000m"
        #  memory: "6144Mi"
      annotations: {}     
          
    service:
      type: ClusterIP
      port: 443  
      annotations:
        # com.palantir.rubix.service.spp/v3: >
        #        {
        #            "endpoints":[{
        #                "name":"<port name from k8s service>",
        #                "prefix":"/genai-pdf",
        #                "prefix-rewrite":"/", 
        #                "domain-aliases":["DEFAULT"]
        #            }]
        #        }
           # This creates a secret called 'cert-<svc-name>' which is needed for frontdoor ingress
        com.palantir.rubix.service/pod-cert: '{}'