---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etlworks-efs-pv
  namespace: duploservices-stg-3p01
spec:
  capacity:
    storage: 5Gi  # This is a placeholder; EFS provides virtually unlimited storage.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # EFS supports multiple nodes accessing the volume
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08146f0ec1dcde3b9  # Your EFS ID # Use HelM Chart to make dynamic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etlworks-efs-pvc
  namespace: duploservices-stg-3p01
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: etlworks-efs-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etlworks-app
  namespace: duploservices-stg-3p01
  labels:
    app: etlworks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etlworks-app
  template:
    metadata:
      labels:
        app: etlworks-app
    spec:
      nodeSelector:
        tenantname: duploservices-stg-3p01
      initContainers:
        - name: download-license
          image: amazon/aws-cli
          command: ["/bin/sh", "-c"]
          args:
            - aws s3 cp s3://duploservices-stg-3p01-etlworks/0e522bc2-11cf-4190-9beb-f935e2f39049.lic /opt/etlworks/data/ &&
              echo "License file downloaded successfully";
          volumeMounts:
            - mountPath: /opt/etlworks/data
              name: etlworks-storage
          env:
            - name: AWS_REGION
              value: "us-gov-west-1"
      containers:
        - name: etlworks-app
          image: etlworks/etlworks-app
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: etlworks
                  key: ETLWORKS_HOST
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: etlworks
                  key: ETLWORKS_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etlworks
                  key: ETLWORKS_PASSWORD
            - name: POSTGRES_PORT
              value: "5432"
            - name: REDIS_HOST # Use HelM Chart to make dynamic
              value: "etlworks-redis-master.duploservices-stg-3p01.svc.cluster.local"
            - name: REDIS_PORT # Use HelM Chart to make dynamic
              value: "6379"
            - name: CUSTOM_PROPERTIES_PREFIX
              value: "spring.redis.password="
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etlworks-redis
                  key: redis-password
            - name: CUSTOM_PROPERTIES
              value: "$(CUSTOM_PROPERTIES_PREFIX)$(REDIS_PASSWORD)"
          volumeMounts:
            - mountPath: /opt/etlworks/data
              name: etlworks-storage
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "2"
              memory: "8Gi"
            limits:
              cpu: "2"
              memory: "8Gi"
      volumes:
        - name: etlworks-storage
          persistentVolumeClaim:
            claimName: etlworks-efs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: etlworks-app
  namespace: duploservices-stg-3p01
  labels:
    app: etlworks-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-00507881a9d442a00, subnet-0c4b81b03e65a4ebf
    external-dns.alpha.kubernetes.io/hostname: etlworks-stg-3p01.authorium.com
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0bf3248f559608753, sg-07e88d2f9bdb09a92
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws-us-gov:acm:us-gov-west-1:070029289390:certificate/33353efb-210b-4a9b-80c4-7df5a5eca554"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  selector:
    app: etlworks-app
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP