apiVersion: v1
kind: Pod
metadata:
  name: redis-cli-test
  namespace: duploservices-stg-3p01
spec:
  nodeSelector:
    tenantname: duploservices-stg-3p01
  containers:
    - name: redis-cli
      image: redis:7.2.4
      command: ["sleep", "3600"] # Keeps the container running for manual testing
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "128Mi"
